apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-filter
  labels:
    app: iris-filter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-filter
  template:
    metadata:
      labels:
        app: iris-filter
    spec:
      containers:
      - name: iris
        image: varun2k4/iris_datafilter:latest
        ports:
        - containerPort: 8000
